In [1]:
import numpy as np
np.random.seed(0)
N=6
Arreglo=(np.random.random((N,N))*10.0)-5.0
B=(np.random.random((N,1))*10.0)-5.0

In [2]:
# Gauss Jordan
Ab = np.concatenate((Arreglo,B),axis=1)
for i in range(N):
  Ab[i] = Ab[i]/Ab[i,i]
  for j in range(i+1,N):
    Ab[j] = Ab[j] - Ab[i]*Ab[j,i]
  for k in range(i-1,-1,-1):
    Ab[k] = Ab[k] - Ab[i]*Ab[k,i]

xgj = Ab[:,-1]

In [3]:
xgj = xgj.reshape(N,1)
print(xgj)

[[ 0.50049575]
 [ 0.47054846]
 [-0.29190397]
 [-0.22240309]
 [ 0.22167228]
 [ 0.29686295]]


In [4]:
# Gauss
Ab = np.concatenate((Arreglo,B),axis=1)
for i in range(N):
  Ab[i] = Ab[i]/Ab[i,i]
  for j in range(i+1,N):
    Ab[j] = Ab[j] - Ab[i]*Ab[j,i]

A = Ab[:,:-1]
b = Ab[:,-1]

xg = np.zeros(N)
for i in range(N-1,-1,-1):
  xi = b[i] - np.dot(A[i], xg)
  xg[i] = xi

In [5]:
xg = xg.reshape(N,1)
print(xg)

[[ 0.50049575]
 [ 0.47054846]
 [-0.29190397]
 [-0.22240309]
 [ 0.22167228]
 [ 0.29686295]]


In [6]:
# Numpy
xnumpy = np.linalg.solve(Arreglo,B)
print(xnumpy)

[[ 0.50049575]
 [ 0.47054846]
 [-0.29190397]
 [-0.22240309]
 [ 0.22167228]
 [ 0.29686295]]


In [7]:
print(f"Error Gauss Jordan - Numpy: {np.max(np.abs(xgj-xnumpy))}")
print(f"Error Gauss - Numpy       : {np.max(np.abs(xg-xnumpy))}")


Error Gauss Jordan - Numpy: 1.1657341758564144e-15
Error Gauss - Numpy       : 1.1657341758564144e-15
