PYTHON: INTRODUCCION (O REPASO)

Tutoriales Python:

learnpython.org

https://www.geeksforgeeks.org/python-programming-language/?ref=lbp

https://argentinaenpython.com/quiero-aprender-python/TutorialPython3.pdf

https://www.youtube.com/playlist?list=PLU8oAlHdN5BlvPxziopYZRd55pdqFwkeS

https://www.freecodecamp.org/learn/scientific-computing-with-python/#python-for-everybody



IMPRIMIR EN LA TERMINAL:

In [1]:
#primer codigo: "hola mundo"
print("hola mundo")

hola mundo


TIPOS DE VARIABLES:

In [2]:
#enteras
mi_ent=3

#flotates
mi_float=4.0

#boleanas
mi_bol=True

#caracteres
mi_car = "hola"
mi_car2='hola2'

print("variable: ", mi_ent)
print("tipo de variable: ", type(mi_ent))
 #mini ejercicio: impriman las otras variables y su tipo

print()

print("variable: ", mi_float)
print("tipo de variable: ", type(mi_float))
print()

print("variable: ", mi_bol)
print("tipo de variable: ", type(mi_bol))
print()

print("variable: ", mi_car)
print("tipo de variable: ", type(mi_car))
print()

print("variable: ", mi_car2)
print("tipo de variable: ", type(mi_car2))
print()

variable:  3
tipo de variable:  <class 'int'>

variable:  4.0
tipo de variable:  <class 'float'>

variable:  True
tipo de variable:  <class 'bool'>

variable:  hola
tipo de variable:  <class 'str'>

variable:  hola2
tipo de variable:  <class 'str'>



OPERACIONES MATEMÁTICAS BÁSICAS

In [3]:
#operaciones basicas entre variables
suma = mi_ent + mi_float
#print(suma)

suma2= mi_car + " " + mi_car2
#print(suma2)

#	NO FUNCIONA
#suma_que_no_funciona = mi_ent + mi_car
#print(suma_que_no_funciona)

#mini ejercicio: descomenten lo anterior y entiendan cuál es el error
suma_que_no_funciona = mi_ent + mi_car #error
print(suma_que_no_funciona)

#No se acepta sumar variables tipo "int" (entero) con "str" (cadena dee caractéres)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

LISTAS y APPEND

In [4]:
#listas
#defino lista vacia:
mi_lista=[]
#print(mi_lista)

#le agrego un elemento
mi_lista.append(27.0)
#print(mi_lista)

#le agrego otro elemento
mi_lista.append(12)
#print(mi_lista)

#le agrego varios elementos
mi_lista.append(45)
mi_lista.append(5.2)
mi_lista.append(17)
mi_lista.append(22)

print("mi lista: ", mi_lista)

#imprimo el primer elemento de la lista
print("primer elemento: ", mi_lista[0])

#mini ejercicio: imprima el tercer elemento:
print("primer elemento: ", mi_lista[2])

#otra forma de definir listas:
mi_lista2=[12,34,56,67,87,65,45.0]
print("mi_lista2: ", mi_lista2)

#las listas pueden tener todo tipo de variables
mi_lista3=[12, 34.0, "gato", True, 34.56]
print("mi_lista3: ", mi_lista3)

#mini ejercicio: qué pasa si sumo mi_lista2 con mi_lista3? imprima el resultado
mi_suma=mi_lista2 + mi_lista3
print("suma de mi_lista2 y mi_lista3: ", mi_suma)

#mini ejercicio: qué pasa si multiplico mi_lista2 por 3
prod_lista= mi_lista2*3
print("mi_lista2 x 2: ", prod_lista)

#mini ejercicio: qué pasa si multiplico mi_lista por mi_lista2?
prod_listas = mi_lista*mi_lista2 #error

# No se acepta el operador multiplicación * entre listas

mi lista:  [27.0, 12, 45, 5.2, 17, 22]
primer elemento:  27.0
primer elemento:  45
mi_lista2:  [12, 34, 56, 67, 87, 65, 45.0]
mi_lista3:  [12, 34.0, 'gato', True, 34.56]
suma de mi_lista2 y mi_lista3:  [12, 34, 56, 67, 87, 65, 45.0, 12, 34.0, 'gato', True, 34.56]
mi_lista2 x 2:  [12, 34, 56, 67, 87, 65, 45.0, 12, 34, 56, 67, 87, 65, 45.0, 12, 34, 56, 67, 87, 65, 45.0]


TypeError: can't multiply sequence by non-int of type 'list'

OPERADORES ARITMÉTICOS BÁSICOS

In [1]:
#operadores aritmeticos basicos
a=12.5
b=3
c=15
#suma
suma=a+b
#resta
resta=a-b
#producto
a*b
#division
a/b
#potencia
a**b
#modulo
a%b

#mini ejercicio: imprima los resultados de las operaciones anteriores
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)
print(a%b)
print()

# errores numéricos
suma1=1+(1.5e56-1.5e56)
suma2=(1+1.5e56)-1.5e56
print(suma1)
print(suma2)

15.5
9.5
37.5
4.166666666666667
1953.125
0.5

1.0
0.0


OPERADORES BÁSICOS DE COMPARACIÓN

In [7]:
#operadores de comparacion basicos
a=12.5
b=3
c=15
#igual que
a==b
#diferente de
a!=b
#mayor que
a>b
#menor que
a<b
#mayor o igual
a>=b
#menor o igual
a<=b

#mini ejercicio: imprima el resultado de las comparaciones anteriores. qué tipo de variable es?
print(a==b)
print(a!=b)
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)

# Todas son variables tipo bool (True o False)

#otros operadores de comparación: https://www.tutorialspoint.com/python/python_basic_operators.htm

False
True
True
False
True
False


CICLOS FOR

In [2]:
#ciclos con la función range
for i in range(10):
  print("i: ", i)

#mini ejercicio: mire la documentación de range (por ejemplo acá: https://www.w3schools.com/python/ref_func_range.asp)
# y haga que i vaya de -10 a 10 en pasos de 2.
print()
for i in range(-10,11,2):
  print("i: ", i)
print()


#ciclos recorriendo listas o arreglos

lista4=[2,3,4,5,6.0,"gato"]
for elemento in lista4:
  print("elemento: ", elemento)



i:  0
i:  1
i:  2
i:  3
i:  4
i:  5
i:  6
i:  7
i:  8
i:  9

i:  -10
i:  -8
i:  -6
i:  -4
i:  -2
i:  0
i:  2
i:  4
i:  6
i:  8
i:  10

elemento:  2
elemento:  3
elemento:  4
elemento:  5
elemento:  6.0
elemento:  gato


NOTA IMPORTANTE!!! LA INDENTACIÓN SE UTILIZA PARA INDICAR QUÉ INSTRUCCIONES ESTÁN DENTRO DEL CICLO (O DENTRO DEL CONDICIONAL, O DENTRO DE LA FUNCION)...


In [3]:
# mini ejercicio: preube los dos ciclos que están a continuación. Cuál es la diferencia?
for j in range(3):
  print("j: ", j)
  print("j+2: ", j+2) #nota: cuidado con el copy paste!!!!

for k in range(3):
  print("k: ", k)
print("k+2: ", k+2)

# El comando "print("k+2: ", k+2)" no se encuentra indentado dentro del ciclo de k, por lo que solo se correrá una vez cuando se cierre el ciclo de k, con k=2.

j:  0
j+2:  2
j:  1
j+2:  3
j:  2
j+2:  4
k:  0
k:  1
k:  2
k+2:  4


ARREGLOS DE NUMPY

In [4]:

#numpy arrays

#import la librería de numpy para poder usar arreglos
import numpy as np

#genero un arreglo de ceros de 10 elementos:
arreglo=np.zeros(10)
print(arreglo)

#remplazo los ceros del arreglo por otro valor usando un ciclo (ver la celda de más adelante)
for i in range(10):
	arreglo[i]=(i-2)**3
print(arreglo)


#mini ejercicio: multiplique el arreglo por 3 e imprima el resultado. Qué diferencia hay con las listas?
print(arreglo*3)

# El operador * entre un número real y un arreglo, multiplica cada elemento del arreglo por el número.
# El operador * entre un entero n y una lista, extiende la lista n veces repitiendo los elementos.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ -8.  -1.   0.   1.   8.  27.  64. 125. 216. 343.]
[ -24.   -3.    0.    3.   24.   81.  192.  375.  648. 1029.]


SLICING DE ARREGLOS DE NUMPY

In [5]:
print("todo", arreglo)
print("[1:3]", arreglo[1:3])
print("[:3]", arreglo[:3])
print("[3:]", arreglo[3:])
print("[-3:]", arreglo[-3:])
print("[3:-3]", arreglo[3: -3])
print("[3:-3: 2]", arreglo[3: -3: 2])

todo [ -8.  -1.   0.   1.   8.  27.  64. 125. 216. 343.]
[1:3] [-1.  0.]
[:3] [-8. -1.  0.]
[3:] [  1.   8.  27.  64. 125. 216. 343.]
[-3:] [125. 216. 343.]
[3:-3] [ 1.  8. 27. 64.]
[3:-3: 2] [ 1. 27.]


CONDICIONALES

In [6]:
var1=17
var2=25
var3=13
lista_var=[12, 45, 17, 13]

#if else
if(var1>=var2):
	print(var1)
else:
	print(var2)

#if elif else
if(var1>=var3):
	print(var1)
elif(var2>=var3):
	print(var2)
else:
	print(var3)


# or y and

if(var1>var3 and var2>var3):
	print(var3)

if(var1<var3 or var2<var3):
	print(var3)


# in y not
if(var1 in lista_var):
	print("verdadero")


if(var2 not in lista_var):
	print("falso")


25
17
13
verdadero
falso


WHILE

In [7]:
#while

j=10

while(j<120):
	print(j)
	#ojo:
	j+=15

10
25
40
55
70
85
100
115


FUNCIONES

In [9]:
#defino una función que llamo mi_funcion. Uso la indentación para indicar qué está dentro de mi función
def mi_funcion(parametro1, parametro2):
  #la función imprime el parametro1
	print("parametro1= ", parametro1)
  #la función retorna el parametro2
	return parametro2**2

#llamo mi mi funcion con los valores 3 y 4 y almaceno lo que retorna mi_funcion en la variable resultado
resultado=mi_funcion(3,4)
print("resultado", resultado)

#mini ejercicio: prueben qué pasa si quieren imprimir la variable parametro2 por fuera de la función
print(parametro2) #error

# Produce error porque no se ha definido la variable parametro2 por fuera de la función, solo aparece como el nombre de la segunda entrada de mi_funcion.

parametro1=  3
resultado 16


NameError: name 'parametro2' is not defined

++++++++++++++++++++++++++++++++++++++++++ EJERCICIOS
 ++++++++++++++++++++++++++++++++++++++++++

EJERCICIO 1:

In [12]:
#ejercicio 1

print("Ejercicio 1")

#a) Inicializar dos variables globales (con valores escogidos por ustedes), una entera y otra flotante.\\


#b) Imprimir los valores de las variables en un mensaje: #
#"La primera tiene un valor de XX y la segunda variable tiene un valor de YY"
x = 4
y = 6.2

print(f"La primera tiene un valor de {x} y la segunda variable tiene un valor de {y}")
print()

#c) Calcular el valor de la segunda variable dividida por la primera e imprimir : "El resultado es ZZ"
z = y/x
print(f"El resultado es {z}")

#d) Crear una lista con los elementos: 101, 26, rio, gato, 17, 45 y 28 e imprimirla.
L = [101,26,"rio","gato",17,45,28]
print(L)
print()

#e) Agregarle a esa lista los elementos: 257, 285, 583
L = L+[257,285,583]

#f) Hacer un ciclo para recorrer dicha lista e imprimir sus elementos.
for i in L:
  print(i)
print()

#g) imprimir el cuarto elemento de la lista.
print(L[3])
print()

#h) Calcular la longitud de la lista e imprimir: "la longitud de la lista es XX" puede usar le función len()
l = len(L)
print(f"La longitud de la lista es {l}")


Ejercicio 1
La primera tiene un valor de 4 y la segunda variable tiene un valor de 6.2

El resultado es 1.55
[101, 26, 'rio', 'gato', 17, 45, 28]

101
26
rio
gato
17
45
28
257
285
583

gato

La longitud de la lista es 10


EJERCICIO 2:

In [16]:
#ejercicio 2
print("Ejercicio 2")

# Complete el siguiente código para que:
# recorra el arreglo `x`
# imprima los números impares
# y pare de imprimir al encontrar un número mayor a 700

import numpy as np

#genero un arreglo de número aleatorios:
x=np.int_(np.random.random(100)*900)
print("arreglo x: ", x)
print()
for i in x:
  if i>700:
    break
  if i%2!=0:
    print(i)




Ejercicio 2
arreglo x:  [ 91 261 225 145 657 383 332  26 783 506 626 683 651  32 472 891 435 323
 788 462 128 599 719  43 334 134 526 316 395 773 153  25 439 854 730 758
 335 847 316 381 419  50 203   6 324  89 276 540 164 149 709 175 640  53
  57 462 403 189 787 289 476 804 188  83 791 826 643 568 181 397 476 169
 695 559 211 485 773 264 668 617 325 240 530 345 629 656 191 686 693 565
 470 783 325 856 498 754 659 277   6 395]

91
261
225
145
657
383


EJERCICIO 3:

In [14]:
#ejercicio 3
print("Ejercicio 3")

#Haga una función llamada multiplicación
#que reciba como argumentos dos variables a y b y retorne a*b.
#Imprima lo que retorna la función para a=10 y b=18
def multiplicacion(a,b):
  return a*b


ejercicio 3


EJERCICIO 4

In [37]:
#ejercicio 4
print("Ejercicio 4")
# Complete el siguiente código para que:
# recorra la lista x del ejercicio 2 y encuentre el mínimo de los elementos de la lista.
#Compare su resultado con el obtenido por np.min e imprima un mensajito con ambos valores.
a = x[0]
for i in x:
  if i<a:
    a=i

print("Mínimo:",a)
print("Mínimo:",np.min(x))


ejercicio 4
Mínimo: 3
Mínimo: 3


EJERCICIO 5

In [17]:
#ejercicio 5
print("Ejercicio 5")
#  sin usar ciclos, sume los 10 primeros elementos del arreglo x a los 10 últimos elementos del arreglo x. Imprima el arreglo resultante.
import numpy as np

#genero un arreglo de número aleatorios:
x=np.int_(np.random.random(100)*900)
print("arreglo x: ", x)
print()
suma = x[:10] + x[-10:]
print(suma)

ejercicio 5
arreglo x:  [318  68 447 708 616 828 833 315 392 665 540  20 729 528 896  48 193 795
 816 295 679 524 779 178 642 863 231 206 586 360 366 248 185  28 671 133
 691   5  71  70 425 713 292 151 422 467 511 542 489 522 649 739 522 713
 856 856 814 535 199 359 106 728 795 490  49 603 784 695 285 718 593 407
 777 757  89 891 752 188 750 363 464  61  31 700 557 816 739 818 150 753
   1 297 834 168 763 524  93 600 114 147]

[ 319  365 1281  876 1379 1352  926  915  506  812]
